[package]
name = "audiomolekula_audio"
version = "0.1.0"
edition = "2024"

[dependencies]
audiomolekula_shared = { path = "../audiomolekula_shared" }
clap-sys = "0.5.0"
cpal = { version = "0.17.1", features = ["asio"] }
libloading = "0.9.0"
rand = "0.9.2"
