[package]
name = "audiomelanakolia"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.0"
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["standalone"] }
serde = { version = "1.0", features = ["derive"] }
