[package]
name = "hopelesslydisturbeddreams"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = "0.8.4"
lazy_static = "1.5.0"
parking_lot = "0.12.5"
serde = "1.0.228"
serde_json = "1.0.149"
widestring = "1.2.1"
