[package]
name = "goldsilverinit"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl2 = { version = "0.38.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
