[package]
name = "hellocpal"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.0"
bevy_egui = "0.39.0"
clap-sys = "0.5.0"
cpal = { version = "*", features = ["asio"] }
libloading = "0.9.0"
