[package]
name = "audiomolekula"
version = "0.1.0"
edition = "2024"

[dependencies]
audiomolekula_core = { path = "audiomolekula_core" }

[workspace]
members = [
  "audiomolekula_core",
]
resolver = "3"