[package]
name = "audiojanuaryone"
version = "0.1.0"
edition = "2024"

[lib]
name = "audiojanuaryone_lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug_iced = { git = "https://github.com/robbert-vdh/nih-plug.git" }