[package]
name = "returntomidir"
version = "0.1.0"
edition = "2024"

[dependencies]
midir = "0.10.3"
axum = { version = "0.8.8", features = ["json"] }
rand = "0.10.0-rc.6"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }