[package]
name = "moradotase"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.23.0"

[dependencies]
lalrpop-util = { version = "0.23.0", features = ["lexer", "unicode"] }
pretty_assertions = "1.4.1"
